version: '3.8'
services:
  keycloak-postgres:
    container_name: keycloak-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-keycloak}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-keycloak}
      POSTGRES_DB: keycloak
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev","--import-realm" ]
    environment:
      DB_VENDOR: POSTGRESQL
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-postgres

volumes:
  postgres: