version: "3.8"
services:
  postgres:
    container_name: postgres_container_inventory
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: inventory_service
    #      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    #      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
    restart: unless-stopped

volumes:
  postgres:
  pgadmin: